<?php

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\hr_smartcard\Controller\TokenCommonFunction;
use Drupal\file\Entity\File;
use Drupal\media_entity\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Template\Attribute;

$config = \Drupal::config('tokenConfigForm.settings');
$GLOBALS['apikey'] = $config->get('apikey');
$GLOBALS['secretkey'] = $config->get('secretkey');
$GLOBALS['jwt_token'] = $config->get('jwt_token');
$GLOBALS['api_url'] = $config->get('api_url');

/**
 * Hook Form Alter
 */
function hr_smartcard_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//    echo $form_id;exit;
 //for generailzed module : pass the machine name of the content type in below condition
//ex : if($form_id == 'node_page_form' || $form_id == 'node_page_edit_form' || $form_id == 'node_article_form'  )


    if($form_id == 'node_page_form' || $form_id == 'node_page_edit_form' ){
       $form['actions']['submit']['#submit'][] = 'hr_smartcard_submit'; 
    }
 
}

/**
 * @file
 * Hook form Submit.
 */
function hr_smartcard_submit($form, &$form_state) {
  
 
  $imageids =  $form_state->getValue('field_image')[0]['fids'];
  if(!empty($imageids)){
       $fid_url = get_image_url_fids($imageids[0]);
  }
  $url =  $form_state->getValue('field_url')[0]['value'];
    $title_smartcard =  $form_state->getValue('title')[0]['value'];
    $createcard = new \Drupal\hr_smartcard\Controller\TokenCommonFunction();
    $response = $createcard->smartCardCurl($title_smartcard,$fid_url,$url);
//   dump($response);exit;
}

function get_image_url_fids($id) {
        $file = File::load($id);
        if ($file) {
            $uri = $file->getFileUri();
        }
        if ($uri) {
            $url = file_create_url($uri);
        }
        return $url;
    }
