<?php

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\hr_smartcard\Controller\TokenCommonFunction;
use Drupal\file\Entity\File;
use Drupal\media_entity\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Template\Attribute;

$config = \Drupal::config('tokenConfigForm.settings');
$GLOBALS['apikey'] = $config->get('apikey');
$GLOBALS['secretkey'] = $config->get('secretkey');
$GLOBALS['jwt_token'] = $config->get('jwt_token');
$GLOBALS['api_url'] = $config->get('api_url');

/**
 * Hook Form Alter
 */
function hr_smartcard_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    if($form_id == 'node_page_form'){
       $form['actions']['submit']['#submit'][] = 'hr_smartcard_submit'; 
    }
 
}

/**
 * @file
 * Hook form Submit.
 */
function hr_smartcard_submit($form, &$form_state) {
    $title_smartcard =  $form_state->getValue('title')[0]['value'];
    $createcard = new \Drupal\hr_smartcard\Controller\TokenCommonFunction($title_smartcard);
   $response = $createcard->smartCardCurl($title_smartcard);
//   dump($response);exit;
}
